name: _dynamite
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/dynamite
  - packages/dynamite/example
  - packages/dynamite_end_to_end_test
  - packages/dynamite_runtime

dev_dependencies:
  build_runner: ^2.12.0
  lint_maker: ^0.3.2
  melos: ^7.5.1

melos:
  repository: https://github.com/provokateurin/dynamite

  ide:
    intellij:
      enabled: false

  scripts:
    test:
      description: Tests all packages with coverage.
      run: dart test
      exec:
        concurrency: 1
        failFast: true
        orderDependents: true
      packageFilters:
        dependsOn:
          - test
        dirExists: test
    generate:
      description: Generate build output for every package.
      run: >
        dart run build_runner build --delete-conflicting-outputs &&
        dart fix --apply &&
        dart format . &&
        dart fix --apply &&
        dart format .
      exec:
        concurrency: 1
        failFast: true
        orderDependents: true
      packageFilters:
        fileExists: build.yaml
    lint_maker:
      description: Update analysis_options with new lint rules.
      run: dart run lint_maker
